package:
  name: codar2netcdf
  version: "1.0.0"

source:
    path: ../

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - pytest
    - pandas
    - netcdf4
    - pytz
    - python-dateutil

  run:
    - python
    - pandas
    - netcdf4
    - pytz
    - python-dateutil

test:
  imports:
    - codar2netcdf
    - codar2netcdf.tests

  requires:
    - pytest

about:
  home: https://github.com/axiom-data-science/codar2netcdf
  license: MIT License
  summary: 'A utility to convert CODAR total ASCII files into CF NetCDF files.'
